QGothic: Move::setFrom
Move & Move::setFrom (const Location & location)
Sets from location of this move.
Parameters
location Location to set.
Returns
Method returns reference to the actual Move instance.
Definition at line 29 of file move.cpp.
Referenced by Referee::getPawnJumps(), Referee::getPawnMoves(), Referee::getQueenJumps(), and Referee::getQueenMoves().
{
    *m_from = location;
    return *this;
}