QGothic: Referee::getAllPawnMoves
getAllMoves
getAllPawnMoves
getAllQueenMoves
getBestMoves
getMoves
getPawnDirections
getPawnJumps
getPawnMoves
getQueenDirections
getQueenJumps
getQueenMoves
isInQueenArea
s_pawnDirections
s_queenDirections
QList< Move > Referee::getAllPawnMoves (const Location & location, Board & board) static
Finds both jumps/moves for pawn.
Parameters
location Position of pawn on the board.
board Board to search the moves on.
Returns
Method returns found jumps/moves.
Definition at line 44 of file referee.cpp.
References getPawnJumps(), and getPawnMoves().
Referenced by getAllMoves().
{
    QList<Move> moves = getPawnJumps(location, board);
    if (moves.size() > 0) {
        return moves;
    }
    else {
        return getPawnMoves(location, board);
    }
}