QGothic: Move::setTo
addJumpedFigure
addJumpedFigure
addJumpedFigures
getFigureType
getFrom
getInvalidMove
getJumpedFigures
getPromoted
getTo
Move
Move
price
setFigureType
setFrom
setPromoted
setTo
void Move::setTo (const Location & location)
Sets to Location of this move.
Parameters
location Location to set.
Definition at line 37 of file move.cpp.
Referenced by Referee::getPawnJumps(), Referee::getPawnMoves(), Referee::getQueenJumps(), and Referee::getQueenMoves().
{
    *m_to = location;
}