QGothic: Referee::getQueenMoves
getAllMoves
getAllPawnMoves
getAllQueenMoves
getBestMoves
getMoves
getPawnDirections
getPawnJumps
getPawnMoves
getQueenDirections
getQueenJumps
getQueenMoves
isInQueenArea
s_pawnDirections
s_queenDirections
QList< Move > Referee::getQueenMoves (const Location & location, Board & board) static
Finds all posibble simple moves (without jumps) for queen.
Parameters
location Position of queen on the board.
board Board to search the moves on.
Returns
Method returns list of found moves or empty list if no moves are available.
Definition at line 216 of file referee.cpp.
References getQueenDirections(), Move::setFigureType(), Move::setFrom(), and Move::setTo().
Referenced by getAllQueenMoves().
{
    QList<Move> moves;
    foreach (Location dir, getQueenDirections()) {
        Location current_location(location);
        for (int i = 0; i < board.getSize()-1; i++) {
            current_location += dir;
            if (current_location.isOnBoard(board)) {
                if (board(current_location) == Figure::EMPTY) {
                    Move move;
                    move.setFrom(location);
                    move.setTo(current_location);
                    move.setFigureType(board(location));
                    moves.append(move);
                }
                else {
                    break;
                }
            }
            else {
                break;
            }
        }
    }
    return moves;
}