QGothic: Referee::getPawnMoves
getAllMoves
getAllPawnMoves
getAllQueenMoves
getBestMoves
getMoves
getPawnDirections
getPawnJumps
getPawnMoves
getQueenDirections
getQueenJumps
getQueenMoves
isInQueenArea
s_pawnDirections
s_queenDirections
QList< Move > Referee::getPawnMoves (const Location & location, Board & board) static
Finds all posibble simple moves (without jumps) for pawn.
Parameters
location Position of pawn on the board.
board Board to search the moves on.
Returns
Method returns list of found moves or empty list if no moves are available.
Definition at line 194 of file referee.cpp.
References Move::getFrom(), getPawnDirections(), Move::getTo(), isInQueenArea(), Move::setFigureType(), Move::setFrom(), Move::setPromoted(), and Move::setTo().
Referenced by getAllPawnMoves().
{
    QList<Move> moves;
    foreach (Location dir, getPawnDirections()) {
        Location current_location = Figure::getTypesByColor(Figure::WHITE).contains(board(location)) ?
                                        location + dir :
                                        location + !dir;
        if (current_location.isOnBoard(board)) {
            if (board(current_location) == Figure::EMPTY) {
                Move move;
                move.setFrom(location);
                move.setTo(current_location);
                move.setFigureType(board(location));
                if (isInQueenArea(move.getTo(), Figure::getColorByType(board(move.getFrom())), board)) {
                    move.setPromoted(true);
                }
                moves.append(move);
            }
        }
    }
    return moves;
}