QGothic: Referee::getQueenJumps
getAllMoves
getAllPawnMoves
getAllQueenMoves
getBestMoves
getMoves
getPawnDirections
getPawnJumps
getPawnMoves
getQueenDirections
getQueenJumps
getQueenMoves
isInQueenArea
s_pawnDirections
s_queenDirections
QList< Move > Referee::getQueenJumps (const Location & location, Board & board) static
Finds all posibble jumps for queen.
Parameters
location Position of queen on the board.
board Board to search the moves on.
Returns
Method returns list of found jumps or empty list if no jumps are available.
Definition at line 85 of file referee.cpp.
References Move::addJumpedFigure(), Move::addJumpedFigures(), Move::getJumpedFigures(), getQueenDirections(), Move::getTo(), Move::setFigureType(), Move::setFrom(), and Move::setTo().
Referenced by getAllQueenMoves().
{
    QList<Move> moves;
    foreach (Location dir, getQueenDirections()) {
        //qDebug() << dir.toString();
        Location current_location(location);
        do {
            current_location += dir;
            // posunuli jsme se na další pozici a kontrolujeme zda na ní je protihráč
            // pokud ano tak skáčeme na libovolnou VOLNOU pozici za tímto kamenem
            if (current_location.isOnBoard(board) && Figure::getColorByType(board(current_location)) == Figure::negateColor(Figure::getColorByType(board(location)))) {
                // posunuli jsme se tedy na prvni pozici za protihráčův kámen
                //qDebug() << board(current_location);
                Location next_location = current_location + dir;
                // dokud je tato pozice volná
                while (next_location.isOnBoard(board) && next_location.isFree(board)) {
                    Move move;
                    move.setFigureType(board(location));
                    move.setFrom(Location(location));
                    move.setTo(Location(next_location));
                    move.addJumpedFigure(current_location, board(current_location));
                    // delame tah a na teto upravene desce hledame dalsi meziskoky z daneho mista
                    board.makeMove(move, false);
                    QList<Move> next_moves = getQueenJumps(next_location, board);
                    // jsou k dispozici dalsi skoky
                    if (next_moves.size() > 0) {
                        foreach (Move next_move, next_moves) {
                            Move final_move(move);
                            final_move.setTo(Location(next_move.getTo()));
                            final_move.addJumpedFigures(next_move.getJumpedFigures());
                            moves.append(final_move);
                        }
                    }
                    else {
                        moves.append(move);
                    }
                    board.makeInverseMove(move, false);
                    next_location += dir;
                }
                break;
            }
        }
        while (current_location.isOnBoard(board) && current_location.isFree(board));
    }
    return moves;
}