#ifndef ALGORITHMS_H
#define ALGORITHMS_H

#include "figure.h"
#include "board.h"

/*!
 * \brief Algorithms used for AI to generate moves.
 * \ingroup Core
 */
class Algorithms {

    public:
	/*!
	 * \brief Used to find the best available Move using Minimax algorithm.
	 * \param original_color
	 * \param actual_color
	 * \param board
	 * \param depth
	 * \return Method returns value generated by board-evaluating functions.
	 */
	static int minimax(Figure::Color original_color, Figure::Color actual_color,
			   Board &board, int depth, int (*eval_function)(Board &));

	static int alfabeta_closer(int price);
	static int alfabeta_further(int price);
	static int alfabeta(Figure::Color original_color, Figure::Color actual_color,
			    Board &board, int depth, int (*eval_function)(Board &),
			    int alfa, int beta);

    private:
	Algorithms();

};

#endif // ALGORITHMS_H
